### ISSUE TITLE
Script doesn't find any video

### ISSUE THREAD

**Issue by dhsdshdhk** [pnbt/youtube-explore#9]
I am trying to run this script every day, and today I ran into this problem:
```

INFO We will NOT be printing keys - False
Running, will save the resulting json to:results/youtube-scrape-2019-08-13.json
Location = None Language = None
Searching for Bolsonaro
Sorting search restuls by relevance
Searching URL: https://www.youtube.com/results?sp=EgIQAQ%253D%253D&q=Bolsonaro
Search results []



Search term = Bolsonaro

counts: {}
 
```

It just won't find anything to continue crawling, despite the fact that we see a bunch of videos in that URL. Did youtube change something to break this script?

**Comment by dhsdshdhk** [comment]
Update: it seems to work sometimes, and finds results for some queries and not for others.

**Comment by dhsdshdhk** [comment]
Found a solution. If you run into this problem or a division by zero problem, it's lxml's fault and you should use Python’s html.parser, BeautifulSoup(html, "html.parser").

**Comment by brunoanuncia** [comment]
> Found a solution. If you run into this problem or a division by zero problem, it's lxml's fault and you should use Python’s html.parser, BeautifulSoup(html, "html.parser").

Sorry if the question sounds stupid, but how do I use Python’s html.parser, BeautifulSoup(html, "html.parser")?

**Comment by brunoanuncia** [comment]
I'm having the same trouble. Python's html.parser solution doesn't work for me. Do you have any other suggestion @dhsdshdhk? Thank you in advance.
